### ISSUE TITLE
TODO/Questions to ask

### ISSUE THREAD

**Issue by andrayantelo** [andrayantelo/calendar-reboot#142]
- [x] In functions like generateEmptyMonthDiv, should I have the divs I'm using hardcoded in? 
- [x] Why does this: http://stackoverflow.com/questions/24320483/define-test-variables-in-qunit-setup 
work?
- [x] What is happening in my fillMonthDiv test?
