### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by andrayantelo** [andrayantelo/calendar-reboot#7]
- [x] Need to use localstorage for storing/loading
- [x] Need to put an input tag where users can pick how many years they want to track 
- [x] Have a max number of years
- [ ] Need to give functions to the buttons
- [ ] Write tests
- [x] Change number of years dropdown so that you don't have to have 20 li tags
